name: Build and Package 2

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            run: "gradle clean downloadJavaFXLibraries"
          - os: windows-latest
            run: "gradlew.bat clean downloadJavaFXLibraries"
          - os: macos-latest
            run: "./gradlew clean downloadJavaFXLibraries"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ${{ matrix.run }}

